// WARNING: This file has automatically been generated on Mon, 10 Jun 2024 17:31:27 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "furiosa/furiosa_smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

