// WARNING: This file has automatically been generated on Fri, 14 Jun 2024 17:29:23 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "furiosa/furiosa_smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

