// WARNING: This file has automatically been generated on Mon, 27 May 2024 16:55:55 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "furiosa_smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

