// WARNING: This file has automatically been generated on Fri, 24 May 2024 14:30:45 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "furiosa_smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

