// WARNING: This file has automatically been generated on Wed, 22 May 2024 16:44:33 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "furiosa-smi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

