// WARNING: This file has automatically been generated on Wed, 22 May 2024 16:44:33 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package binding

/*
#include "furiosa-smi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FuriosaSmiMaxPathSize as defined in furiosa_smi_go/furiosa-smi.h:6
	FuriosaSmiMaxPathSize = 256
	// FuriosaSmiMaxDeviceFileSize as defined in furiosa_smi_go/furiosa-smi.h:8
	FuriosaSmiMaxDeviceFileSize = 64
	// FuriosaSmiMaxCoreStatusSize as defined in furiosa_smi_go/furiosa-smi.h:10
	FuriosaSmiMaxCoreStatusSize = 128
	// FuriosaSmiMaxPeSize as defined in furiosa_smi_go/furiosa-smi.h:12
	FuriosaSmiMaxPeSize = 64
	// FuriosaSmiMaxDriverInfoSize as defined in furiosa_smi_go/furiosa-smi.h:14
	FuriosaSmiMaxDriverInfoSize = 24
	// FuriosaSmiMaxDeviceHandleSize as defined in furiosa_smi_go/furiosa-smi.h:16
	FuriosaSmiMaxDeviceHandleSize = 64
	// FuriosaSmiMaxCstrSize as defined in furiosa_smi_go/furiosa-smi.h:18
	FuriosaSmiMaxCstrSize = 96
)

// FuriosaSmiArch as declared in furiosa_smi_go/furiosa-smi.h:25
type FuriosaSmiArch int32

// FuriosaSmiArch enumeration from furiosa_smi_go/furiosa-smi.h:25
const (
	FuriosaSmiArchWarboy  FuriosaSmiArch = iota
	FuriosaSmiArchRngd    FuriosaSmiArch = 1
	FuriosaSmiArchRngdMax FuriosaSmiArch = 2
	FuriosaSmiArchRngdS   FuriosaSmiArch = 3
)

// FuriosaSmiCoreStatus as declared in furiosa_smi_go/furiosa-smi.h:30
type FuriosaSmiCoreStatus int32

// FuriosaSmiCoreStatus enumeration from furiosa_smi_go/furiosa-smi.h:30
const (
	FuriosaSmiCoreStatusAvailable FuriosaSmiCoreStatus = iota
	FuriosaSmiCoreStatusOccupied  FuriosaSmiCoreStatus = 1
)

// FuriosaSmiDeviceToDeviceLinkType as declared in furiosa_smi_go/furiosa-smi.h:38
type FuriosaSmiDeviceToDeviceLinkType int32

// FuriosaSmiDeviceToDeviceLinkType enumeration from furiosa_smi_go/furiosa-smi.h:38
const (
	FuriosaSmiDeviceToDeviceLinkTypeUnknown      FuriosaSmiDeviceToDeviceLinkType = iota
	FuriosaSmiDeviceToDeviceLinkTypeInterconnect FuriosaSmiDeviceToDeviceLinkType = 10
	FuriosaSmiDeviceToDeviceLinkTypeCpu          FuriosaSmiDeviceToDeviceLinkType = 20
	FuriosaSmiDeviceToDeviceLinkTypeBridge       FuriosaSmiDeviceToDeviceLinkType = 30
	FuriosaSmiDeviceToDeviceLinkTypeSoc          FuriosaSmiDeviceToDeviceLinkType = 70
)

// FuriosaSmiReturnCode as declared in furiosa_smi_go/furiosa-smi.h:53
type FuriosaSmiReturnCode int32

// FuriosaSmiReturnCode enumeration from furiosa_smi_go/furiosa-smi.h:53
const (
	FuriosaSmiReturnCodeOk                       FuriosaSmiReturnCode = iota
	FuriosaSmiReturnCodeInitializeError          FuriosaSmiReturnCode = 1
	FuriosaSmiReturnCodeUninitializedError       FuriosaSmiReturnCode = 2
	FuriosaSmiReturnCodeInvalidArgumentError     FuriosaSmiReturnCode = 3
	FuriosaSmiReturnCodeNullPointerError         FuriosaSmiReturnCode = 4
	FuriosaSmiReturnCodeMaxBufferSizeExceedError FuriosaSmiReturnCode = 5
	FuriosaSmiReturnCodeDeviceFileNotFoundError  FuriosaSmiReturnCode = 6
	FuriosaSmiReturnCodeDeviceFileFormatError    FuriosaSmiReturnCode = 7
	FuriosaSmiReturnCodeDeviceNotInUseError      FuriosaSmiReturnCode = 8
	FuriosaSmiReturnCodeDeviceNodeError          FuriosaSmiReturnCode = 9
	FuriosaSmiReturnCodeParseError               FuriosaSmiReturnCode = 10
	FuriosaSmiReturnCodeUnknownError             FuriosaSmiReturnCode = 11
)
