// WARNING: This file has automatically been generated on Fri, 24 May 2024 14:30:45 KST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package binding

/*
#include "furiosa_smi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FuriosaSmiDeviceHandle type as declared in furiosa_smi_go/furiosa_smi.h:58
type FuriosaSmiDeviceHandle uint32

// FuriosaSmiDeviceHandles as declared in furiosa_smi_go/furiosa_smi.h:63
type FuriosaSmiDeviceHandles struct {
	Count          uint32
	DeviceHandles  [64]FuriosaSmiDeviceHandle
	ref1e2e4077    *C.FuriosaSmiDeviceHandles
	allocs1e2e4077 interface{}
}

// FuriosaSmiVersion as declared in furiosa_smi_go/furiosa_smi.h:71
type FuriosaSmiVersion struct {
	Arch           FuriosaSmiArch
	Major          uint32
	Minor          uint32
	Patch          uint32
	Metadata       [96]byte
	ref2c989684    *C.FuriosaSmiVersion
	allocs2c989684 interface{}
}

// FuriosaSmiDeviceInfo as declared in furiosa_smi_go/furiosa_smi.h:85
type FuriosaSmiDeviceInfo struct {
	Arch            FuriosaSmiArch
	CoreNum         uint32
	NumaNode        uint32
	Name            [96]byte
	Serial          [96]byte
	Uuid            [96]byte
	Bdf             [96]byte
	Major           uint16
	Minor           uint16
	FirmwareVersion FuriosaSmiVersion
	DriverVersion   FuriosaSmiVersion
	refde203aa5     *C.FuriosaSmiDeviceInfo
	allocsde203aa5  interface{}
}

// FuriosaSmiDeviceFile as declared in furiosa_smi_go/furiosa_smi.h:91
type FuriosaSmiDeviceFile struct {
	CoreStart      uint32
	CoreEnd        uint32
	Path           [256]byte
	ref99363de2    *C.FuriosaSmiDeviceFile
	allocs99363de2 interface{}
}

// FuriosaSmiDeviceFiles as declared in furiosa_smi_go/furiosa_smi.h:96
type FuriosaSmiDeviceFiles struct {
	Count          uint32
	DeviceFiles    [64]FuriosaSmiDeviceFile
	ref55937a62    *C.FuriosaSmiDeviceFiles
	allocs55937a62 interface{}
}

// FuriosaSmiCoreStatuses as declared in furiosa_smi_go/furiosa_smi.h:101
type FuriosaSmiCoreStatuses struct {
	Count          uint32
	CoreStatus     [128]FuriosaSmiCoreStatus
	ref2e906eda    *C.FuriosaSmiCoreStatuses
	allocs2e906eda interface{}
}

// FuriosaSmiDeviceErrorInfo as declared in furiosa_smi_go/furiosa_smi.h:113
type FuriosaSmiDeviceErrorInfo struct {
	AxiPostErrorCount      uint32
	AxiFetchErrorCount     uint32
	AxiDiscardErrorCount   uint32
	AxiDoorbellErrorCount  uint32
	PciePostErrorCount     uint32
	PcieFetchErrorCount    uint32
	PcieDiscardErrorCount  uint32
	PcieDoorbellErrorCount uint32
	DeviceErrorCount       uint32
	ref51d9cc38            *C.FuriosaSmiDeviceErrorInfo
	allocs51d9cc38         interface{}
}

// FuriosaSmiDriverInfo as declared in furiosa_smi_go/furiosa_smi.h:118
type FuriosaSmiDriverInfo struct {
	Count          uint32
	DriverInfo     [24]FuriosaSmiVersion
	ref26157232    *C.FuriosaSmiDriverInfo
	allocs26157232 interface{}
}

// FuriosaSmiPeUtilization as declared in furiosa_smi_go/furiosa_smi.h:125
type FuriosaSmiPeUtilization struct {
	CoreCount         uint32
	Cores             [64]uint32
	TimeWindowMil     uint32
	PeUsagePercentage uint32
	ref606fb886       *C.FuriosaSmiPeUtilization
	allocs606fb886    interface{}
}

// FuriosaSmiMemoryUtilization as declared in furiosa_smi_go/furiosa_smi.h:130
type FuriosaSmiMemoryUtilization struct {
	TotalBytes     uint64
	InUseBytes     uint64
	ref7792c50a    *C.FuriosaSmiMemoryUtilization
	allocs7792c50a interface{}
}

// FuriosaSmiDeviceUtilization as declared in furiosa_smi_go/furiosa_smi.h:136
type FuriosaSmiDeviceUtilization struct {
	PeCount        uint32
	Pe             [64]FuriosaSmiPeUtilization
	Memory         FuriosaSmiMemoryUtilization
	ref14f3ecf2    *C.FuriosaSmiDeviceUtilization
	allocs14f3ecf2 interface{}
}

// FuriosaSmiDevicePowerConsumption as declared in furiosa_smi_go/furiosa_smi.h:140
type FuriosaSmiDevicePowerConsumption struct {
	RmsTotal       float64
	ref880dd3b9    *C.FuriosaSmiDevicePowerConsumption
	allocs880dd3b9 interface{}
}

// FuriosaSmiDeviceTemperature as declared in furiosa_smi_go/furiosa_smi.h:145
type FuriosaSmiDeviceTemperature struct {
	SocPeak        int32
	Ambient        int32
	ref3d98ab15    *C.FuriosaSmiDeviceTemperature
	allocs3d98ab15 interface{}
}
