name: Build & Push container image to public registry

on:
  push:
    tags:
      - '*'

jobs:
  public_build_push:
    runs-on: "ubuntu-latest"
    env:
      PUBLIC_REGISTRY_URL: "registry.furiosa.ai"
      PUBLIC_IMAGE_NAME: "furiosa/libfuriosa-kubernetes"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: public registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PUBLIC_REGISTRY_URL }}
          username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
          password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
      - name: Build and publish a image with latest tag
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ env.PUBLIC_REGISTRY_URL }}/${{ env.PUBLIC_IMAGE_NAME }}:latest'
      - name: Build and publish a image with release tag
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ env.PUBLIC_REGISTRY_URL }}/${{ env.PUBLIC_IMAGE_NAME }}:${{github.ref_name}}'
